### ISSUE TITLE
Only let leader compile squad playlist

### ISSUE THREAD

**Issue by JMS55** [hershal-rami/squadify#13]
Hide the button on frontend, check user is leader on backend

**Comment by JMS55** [comment]
Unclear how to do the backend check. `/finish` is both a GET and POST route, but it looks like it does the same thing for both. This should really only create the playlist on POST, and display the finish page on GET (or an error if it doesn't exist).

That's kind of clunky though, we perhaps want to do #18 first, so we can remove the GET aspect of /finish, and make it purely a POST method.

**Comment by jhudis** [comment]
Actually, we don't want to do this. There's no harm in letting any signed-in user compile the squad to their own account.
