### ISSUE TITLE
If playlist name already exists, add a number after it

### ISSUE THREAD

**Issue by JMS55** [hershal-rami/squadify#16]
So if squad name is "Abb", but "Abb" is already a playlist, try "Abb1", etc.

**Comment by hershal-rami** [comment]
in the future, can also add an option for the squad leader to name the playlist

**Comment by jhudis** [comment]
I don't think we actually want to do this. Spotify is happy to make multiple playlists with the same name, plus if a user really does want to make two compilations of the same squad, they'll end up renaming it afterwards anyway.
