### ISSUE TITLE
Handle invalid squad link

### ISSUE THREAD

**Issue by JMS55** [hershal-rami/squadify#43]
Sometimes an invalid squad page leads to an internal server error, and sometimes it gives page not found. The internal server error shouldn't happen.

**Comment by jhudis** [comment]
Figured out the issue. This route expects the squad id to be a uuid. If it's not, it'll return a 404 error, as desired. If it is a uuid but just happens to be one that isn't in our database, it will be able to call the function and hit a NoneType error.
