### ISSUE TITLE
Require 2 playlists minimum to create a squad

### ISSUE THREAD

**Issue by hershal-rami** [hershal-rami/squadify#48]
Grey out squad up button (maybe add filler text) and make unclickable until a squad contains 2 playlists minimum, then change the button back to normal and allow user to create squad

**Comment by JMS55** [comment]
Any changes like this done with JS on the frontend ALSO need to be verified on the backend. We can't rely on the frontend to enforce valid API usage.

**Comment by JMS55** [comment]
Related: https://github.com/hershal-rami/squadify/issues/9

**Comment by JMS55** [comment]
I just added a check on the backend for at least 1 playlist, and if not redirected back to the squad page. Fixed by 1ee995e.
